import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import PageTitle from "./components/PageTitle";
import Image from "next/image";
import NotificationBar from "./components/NotificationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crypto Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen min-w-full flex relative">
          <SideBar />
          <div className="flex flex-col grow main-body min-h-screen text-sm text-[#6F6C99] p-16">
            <div className="flex justify-between items-start">
              <div className="flex flex-col gap-3">
                <PageTitle />
                <p>
                  With all of the styling tool options available in today’s
                  market
                </p>
              </div>
              <NotificationBar />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
